config/routes.rb
PennyEarned::Application.routes.draw do
  get '/assets', to: 'application#assets' if Rails.env == 'development'

  get '/accounts/:id/reviews/:month/:year', to: 'accounts#show', as: 'account_review'
  post '/accounts/:id/calculate_range', to: 'accounts#calculate_range',
    as: 'account_calculate'

  resources :accounts do
    get '/totals', to: 'accounts#totals', as: 'totals'
    get '/min_max', to: 'accounts#min_max', as: 'min_max'
    post '/transactions/bulk/csv/', to: 'transactions#bulk_csv',
      as: 'transactions_bulk_csv'
    get '/transactions/bulk/csv/', to: 'transactions#bulk_csv_new'

    resources :transactions, except: [:edit]
    resources :monthly_reviews, only: [:index]
  end

  devise_for :users

  root to: "accounts#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def create
    transaction = Transaction.new(acceptable_params)
    transaction.account_id = params[:account_id]
    handle_response(transaction) do |success|
      if success
        transaction.update_categories params[:categories]
        transaction.handle_recurrence params[:recurrence]
      end
    end
  end

  def new
    render json: Transaction.new
  end

  def update
    transaction = Transaction.find(params[:id])
    if params[:transaction]
      transaction.update(acceptable_params)
    end
    handle_response(transaction) do |success|
      if success
        transaction.update_categories categories

        if params[:affectSeries] == 'true'
          transaction.handle_recurrence params[:recurrence]
        end

      end
    end
  end

  def show
    render json: Transaction.find(params[:id])
  end

  def index
    @account = Account.find(params[:account_id])
    @time = (params[:year] ? Date.new(params[:year].to_i, params[:month].to_i) : Date.today)
    @transactions = @account.monthly_reviews.at(@time).first.transactions

    render partial: 'accounts/transactions',
      locals: {transactions: @transactions}
  end

  def destroy
    success = false
    transaction = Transaction.find(params[:id])

    if params[:forward_transactions] == 'true'
      transaction.recurrence.update_attribute(:active, false)
      success = transaction.destroy_forward
    else
      success = !!transaction.destroy
    end

    render json: {success: success}
  end

  def bulk_csv
    bulk = BulkTransaction.add(
      params['account_id'], CSVToTransactions.parse(params['csv_file'])
    )

    if bulk === true
      redirect_to account_path(params['account_id'])
    else
      send_data TransactionsArrayToCSV.parse(bulk),
        type: 'text/csv; charset=utf-8; header=present',
        disposition: "attachment; filename=errors-#{Time.new.strftime('%s')}.csv"
    end
  end

  private

  def categories
    return nil if params[:preserve_categories]
    params[:categories] || []
  end

  def acceptable_params
    params.require(:transaction)
      .permit(:account_id, :description, :date, :amount, :state, :debit)
  end
end

app/views/transactions/bulk_csv_new.html.erb
<script>
  var accountId = <%= params[:account_id] %>;
</script>
<%= form_tag({action: :bulk_csv}, id: 'bulk-csv-form', multipart: true) do %>
<div class="row">
    <div class="cell">
        <p>A properly formatted CSV file will have a header row at the top with the related values descending underneath them.</p>
        <p><h4>Proper Headers</h4><ul>
            <li>Date</li>
            <li>Amount</li>
            <li>Debit (conditionally optional)</li>
            <li>State (optional)</li>
            <li>Categories (optional)</li>
            <li>Description (optional)</li>
        </ul>
        <div>
            <h5>Date</h5><ul>
              <li>Needs to be in mm/dd/yyyy format</li>
            </ul>
        </div>
        <div>
            <h5>Amount</h5><ul>
              <li>Preferably <b>without</b> note signifiers like '$'</li>
            </ul>
        </div>
        <div>
            <h5>Debit</h5><ul>
              <li>when true it will mean the related amount is a deduction</li>
              <li>Does not need to be included if amounts are negative and positive</li>
              <li>Will default to true or amount as deduction</li>
              <li>Valid entries are: (case insensitive)
                <ul class="bulletted-list">
                  <li>true or false</li>
                  <li>debit or credit</li>
                </ul>
              </li>
            </ul>
        </div>
        <div>
          <h5>State</h5><ul>
            <li>Valid states include:
              <ul class="bulletted-list">
                <li>placeholder (default)</li>
                <li>Pending</li>
                <li>Paid</li>
              </ul>
            </li>
          </ul>
        </div>
        <div>
            <h5>Categories</h5><ul>
              <li>Should only contain alpha-numerics, spaces, dashes and underscores</li>
              <li>Should be deliminated by either a comma or semi-colon<li>
            </ul>
        </div>
        <div>
            <h5>Description</h5><ul>
              <li>Should only contain alpha-numerics, spaces, dashes and underscores</li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="csv cell">
        <label for="date">CSV File:</label>
        <%= file_field_tag "csv_file" %>
    </div>
</div>
<div class="row">
  <input type="submit" class="submit button primary" value="Submit" />
  <%= link_to 'Cancel', account_transactions_path(params['account_id']), class: "cancel button secondary" %>
</div>
<% end %>