config/routes.rb
PennyEarned::Application.routes.draw do
  get '/assets', to: 'application#assets' if Rails.env == 'development'

  get '/accounts/:id/reviews/:month/:year', to: 'accounts#show', as: 'account_review'
  post '/accounts/:id/calculate_range', to: 'accounts#calculate_range',
    as: 'account_calculate'

  resources :accounts do
    get '/totals', to: 'accounts#totals', as: 'totals'
    get '/min_max', to: 'accounts#min_max', as: 'min_max'
    post '/transactions/bulk/csv/', to: 'transactions#bulk_csv',
      as: 'transactions_bulk_csv'
    get '/transactions/bulk/csv/', to: 'transactions#bulk_csv_new'

    resources :transactions, except: [:edit]
    resources :monthly_reviews, only: [:index]
  end

  devise_for :users

  root to: "accounts#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
  TYPES = [
    'Checking Account',
    'Savings Account',
    'Credit Card'
  ]

  belongs_to :user
  has_many :transactions
  has_many :future_transactions, -> (account) {
    where(date: Date.tomorrow..account.end_date)
  }, class_name: 'Transaction'
  has_many :categories
  has_many :monthly_reviews
  has_many :recurrences, through: :transactions
  has_one :most_recent_transaction, -> {
    where(date: Date.today.beginning_of_month..Date.today)
    .order(date: :desc, created_at: :desc).limit(1)
  }, class_name: 'Transaction'
  has_one :meta

  validates :user_id, :type_of, :name, presence: true
  validates :type_of, :name, presence: true
  validates :type_of, inclusion: { in: TYPES }

  after_save :create_reviews

  def create_reviews
    MonthlyReview.generate_for(self)
  end

  def start_month
    started_date.month
  end

  def start_year
    started_date.year
  end

  def review_for(time)
    monthly_reviews.where(month: time.month, year: time.year).first
  end

  def total
    last_transaction.banked
  end

  def estimated
    last_transaction.estimated
  end

  def calculate_range(start, finish = nil)
    finish = end_date if finish.nil?
    monthly_reviews.where(date: start..finish).each do |review|
      review.calculate_totals
    end
  end

  def end_date
    monthly_reviews
      .order(date: :asc).last.date.end_of_month
  end

  def min
    min_info[:amount]
  end

  def max
    max_info[:amount]
  end

  def min_review
    min_info[:review]
  end

  def max_review
    max_info[:review]
  end

  private

  def last_transaction
    if most_recent_transaction.nil?
      OpenStruct.new(banked: starting_amount, estimated: starting_amount)
    else
      most_recent_transaction
    end
  end

  def min_info
    @min_info ||= {
      transaction: (transaction = future_transactions
        .order(estimated: :asc).first),
      review: review_for(transaction.date),
      amount: transaction.estimated
    }
  end

  def max_info
    @max_info ||= {
      transaction: (transaction = future_transactions
        .order(estimated: :desc).first),
      review: review_for(transaction.date),
      amount: transaction.estimated
    }
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :totals,
    :min_max]
  before_action :authenticate_user!
  before_action :clear_extras, only: :show

  respond_to :html

  def index
    @accounts = Account.where(user_id: current_user.id)
    respond_with(@accounts)
  end

  def show
    if @account.nil?
      redirect_to root_path
    else
      @time = params[:year] ?
        Date.new(params[:year].to_i, params[:month].to_i) : Date.today.beginning_of_month
      @transactions = @account.review_for(@time).transactions

      respond_with(@account)
    end
  end

  def new
    @account = Account.new
    respond_with(@account)
  end

  def edit
  end

  def create
    params[:account][:user_id] = current_user.id

    @account = Account.new(account_params)
    @account.save

    respond_with(@account)
  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end

  def totals
    render partial: 'totals', locals: {account: @account}
  end

  def min_max
    render partial: 'min_max', locals: {account: @account}
  end

  def calculate_range
    @account = Account.find(params[:id])
    start_time = Date.new(params[:start][:year].to_i,
                          params[:start][:month].to_i).beginning_of_month

    unless params[:finish].nil?
      end_time = Date.new(
        params[:finish][:year].to_i, params[:finish][:month].to_i)
        .end_of_month
    end

    @account.calculate_range(start_time, end_time)

    render nothing: true
  end

  private
    def set_account
      @account = Account.where(id: params[:id] || params[:account_id],
        user: current_user).first
    end

    def account_params
      params.require(:account).permit(:user_id, :type_of, :name,
        :starting_date, :starting_amount)
    end

    def clear_extras
      return if @account.nil?
      clear_categories
    end

    def clear_categories
      @account.categories.each do |category|
        category.destroy if category.transactions.empty?
      end
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def error_class(amount, additional_classes = '')
      "class=\"#{(amount.nil? ? false : amount < 0) ? 'error ' : '' }#{additional_classes}\"".html_safe
  end

  def review_shortcut_links
    html = ''
    is_current_month = @time.month == Date.today.month &&
      @time.year == Date.today.year

    previous_review =  @account.review_for @time - 1.months
    next_review = @account.review_for @time + 1.months

    if previous_review
      html << review_link_for(
        previous_review, text: ' ', class: 'fa fa-play-circle previous'
      )
    end

    if is_current_month
      html << 'month'
    else
      html << review_link_for(Date.today, text: 'Current Month')
    end

    if next_review
      html << review_link_for(
        next_review, text: ' ', class: 'fa fa-play-circle'
      )
    end

    html.html_safe
  end

  def review_link_for(review, options = {})
    account = @account || review.account
    link_to (options[:text] || review.date
        .strftime((options[:format] || '%b %Y'))),
      account_review_path(account, review.month, review.year),
      options
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Name:' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :type_of, 'Type:' %>
    <%= f.select :type_of, options_for_select(Account::TYPES) %>
  </div>

  <div class="field">
    <%= f.label :starting_date, 'Starting Date:' %>
    <%= f.text_field :starting_date %>
  </div>

  <div class="field">
    <%= f.label :starting_amount, 'Starting Amount:' %>
    <%= f.text_field :starting_amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_min_max.html.erb
<h3>High and Low Months</h3>
<% if account.future_transactions.count > 0 %>
<div class="row min">
    <%= link_to account.min_review.date.strftime('%b %Y') + ':',
        account_review_path(account.id, account.min_review.month, account.min_review.year) %>
    <span <%= error_class(account.min) %>><%= account.min %></span>
</div>
<div class="row max">
    <%= link_to account.max_review.date.strftime('%b %Y') + ':',
        account_review_path(account.id, account.max_review.month, account.max_review.year) %>
    <span <%= error_class(account.max) %>><%= account.max %></span>
</div>
<% end %>

app/views/accounts/_reviews_selector.html.erb
<%= link_to "#{@time.strftime('%B %Y')} <span class='fa fa-play-circle'></span>".html_safe , '#', data: {review: "#{@time.month}/#{@time.year}"}, class: "main-date" %>
<ul class="date-selector">
    <li class="archive"><%= link_to 'Archive', account_monthly_reviews_path(@account) %></li>
<% @account.monthly_reviews.each do |review| %>
    <% if review.is_in_future? %>
    <li><%= link_to review.date.strftime('%B %Y'), account_review_path(@account, review.month, review.year), data: {review: "#{review.month}/#{review.year}"}, class: @time == review.date ? "selected" : '' %></li>
    <% end %>
<% end %>
</ul>

app/views/accounts/_totals.html.erb
<h3>Current Totals</h3>
<div class="account-total">
    <span class="label">In the bank:</span>
    <span <%= error_class(account.total, 'amount') %>><%= account.total %></span>
</div>
<div class="account-estimated">
    <span class="label">Estimated:</span>
    <span <%= error_class(account.estimated, 'amount') %>><%= account.estimated %></span>
</div>

app/views/accounts/_transactions.html.erb
<div>
<table class="transactions">
    <thead>
        <tr>
            <th>Date</th>
            <th>Info</th>
            <th>Amount</th>
            <th>Banked</th>
            <th>Estimated</th>
            <th>Categories</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <% transactions.reorder(date: :desc, created_at: :desc).each do |transaction|%>
        <tr class="transaction" data-recurring="<%= !!transaction.recurrence_id %>">
            <td><%= transaction.date.strftime('%m/%d/%Y') %></td>
            <td><%= transaction.description %></td>
            <td <%= transaction.debit ? '' : 'class="credit"'.html_safe %>><%= transaction.amount %></td>
            <td <%= error_class(transaction.banked) %>><%= transaction.banked %></td>
            <td <%= error_class(transaction.estimated) %>><%= transaction.estimated %></td>
            <td><%= transaction.categories.collect {|category| category.name}.join(", ") %></td>
            <td>
                <%= link_to '', '#',
                    class: "edit-transaction button icon fa fa-pencil",
                        data: {id: transaction.id} %>
                        <%= link_to '<i class="fa" />'.html_safe, '#',
                    class: "edit-transaction-state button icon fa #{transaction.state}",
                        data: {id: transaction.id, state: transaction.state} %>
                <%= link_to '', '#',
                    class: "delete-transaction button icon fa fa-trash-o",
                        data: {id: transaction.id} %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>
</div>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name:</th>
      <th>Type:</th>
      <th>Total:</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.type_of %></td>
        <td><%= account.total %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<script>
  var accountId = <%= @account.id %>;
  bank.Account.time = {month: <%= @time.month %>, year: <%= @time.year %>}
  bank.accountCategories = <%= @account.categories.collect {|cat| cat.name }.to_s.html_safe %>;
  bank.Account.data = <%= @account.attributes.merge(max_date: (Date.today + MonthlyReview::FUTURE_MONTHS.months).end_of_month).to_json.html_safe %>
</script>

<div class="title-bar">
    <h1><%= @account.name %></h1>
    <%= render partial: 'reviews_selector' %>
</div>
<div class="column left two large">
    <div class="title-area">
        <div class="review-shortcuts">
            <%= review_shortcut_links %>
        </div>
        <div class="transaction-actions">
            <a href="#" class="button general fa fa-plus-circle new-transaction">New Transaction</a>
            <a href="#" class="button general transaction-dropdown">▼</a>
            <ul class="collapsed">
                <%= link_to "Bulk Transaction - CSV", account_transactions_bulk_csv_path(@account),  class: "general bulk-transaction" %>
            </ul>
        </div>
    </div>
    <div class="transactions-wrapper">
        <%= render partial: 'transactions', locals: {transactions: @transactions} %>
    </div>
</div>
<div class="column two small stats">
    <div class="totals-wrapper">
        <%= render partial: 'totals', locals: {account: @account} %>
    </div>
    <div class="min-max-wrapper">
        <%= render partial: 'min_max', locals: {account: @account} %>
    </div>
</div>